/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as signInRouteImport } from './routes/sign-in'
import { Route as credentialsRouteImport } from './routes/credentials'
import { Route as consentRouteImport } from './routes/consent'
import { Route as aboutRouteImport } from './routes/about'
import { Route as indexRouteImport } from './routes/index'
import { Route as ApiGroupsSplatRouteImport } from './routes/api/groups/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as wellKnownOpenidConfigurationRouteImport } from './routes/_well-known/openid-configuration'
import { Route as wellKnownOauthAuthorizationServerRouteImport } from './routes/_well-known/oauth-authorization-server'

const signInRoute = signInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const credentialsRoute = credentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const consentRoute = consentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const aboutRoute = aboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGroupsSplatRoute = ApiGroupsSplatRouteImport.update({
  id: '/api/groups/$',
  path: '/api/groups/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const wellKnownOpenidConfigurationRoute =
  wellKnownOpenidConfigurationRouteImport.update({
    id: '/api/auth/.well-known/openid-configuration',
    path: '/api/auth/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const wellKnownOauthAuthorizationServerRoute =
  wellKnownOauthAuthorizationServerRouteImport.update({
    id: '/api/auth/.well-known/oauth-authorization-server',
    path: '/api/auth/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/about': typeof aboutRoute
  '/consent': typeof consentRoute
  '/credentials': typeof credentialsRoute
  '/sign-in': typeof signInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/groups/$': typeof ApiGroupsSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof wellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof wellKnownOpenidConfigurationRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/about': typeof aboutRoute
  '/consent': typeof consentRoute
  '/credentials': typeof credentialsRoute
  '/sign-in': typeof signInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/groups/$': typeof ApiGroupsSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof wellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof wellKnownOpenidConfigurationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexRoute
  '/about': typeof aboutRoute
  '/consent': typeof consentRoute
  '/credentials': typeof credentialsRoute
  '/sign-in': typeof signInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/groups/$': typeof ApiGroupsSplatRoute
  '/api/auth/.well-known/oauth-authorization-server': typeof wellKnownOauthAuthorizationServerRoute
  '/api/auth/.well-known/openid-configuration': typeof wellKnownOpenidConfigurationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consent'
    | '/credentials'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/groups/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consent'
    | '/credentials'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/groups/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consent'
    | '/credentials'
    | '/sign-in'
    | '/api/auth/$'
    | '/api/groups/$'
    | '/api/auth/.well-known/oauth-authorization-server'
    | '/api/auth/.well-known/openid-configuration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute
  aboutRoute: typeof aboutRoute
  consentRoute: typeof consentRoute
  credentialsRoute: typeof credentialsRoute
  signInRoute: typeof signInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGroupsSplatRoute: typeof ApiGroupsSplatRoute
  wellKnownOauthAuthorizationServerRoute: typeof wellKnownOauthAuthorizationServerRoute
  wellKnownOpenidConfigurationRoute: typeof wellKnownOpenidConfigurationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof signInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof credentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof consentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof aboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/groups/$': {
      id: '/api/groups/$'
      path: '/api/groups/$'
      fullPath: '/api/groups/$'
      preLoaderRoute: typeof ApiGroupsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/.well-known/openid-configuration': {
      id: '/api/auth/.well-known/openid-configuration'
      path: '/api/auth/.well-known/openid-configuration'
      fullPath: '/api/auth/.well-known/openid-configuration'
      preLoaderRoute: typeof wellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/.well-known/oauth-authorization-server': {
      id: '/api/auth/.well-known/oauth-authorization-server'
      path: '/api/auth/.well-known/oauth-authorization-server'
      fullPath: '/api/auth/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof wellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  aboutRoute: aboutRoute,
  consentRoute: consentRoute,
  credentialsRoute: credentialsRoute,
  signInRoute: signInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGroupsSplatRoute: ApiGroupsSplatRoute,
  wellKnownOauthAuthorizationServerRoute:
    wellKnownOauthAuthorizationServerRoute,
  wellKnownOpenidConfigurationRoute: wellKnownOpenidConfigurationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
